### ISSUE TITLE
Github 로그인 처리 시 Refresh Token 발급 오류

### ISSUE THREAD

**Issue by jjangsky** [two-clock/backend#50]
@openmpy 안녕하십니까

이번에 게시글 좋아요 기능#46 을 만들다가 로그인 과정에서 이슈를 발견하여 등록합니다.
확인해보았는데 Github 최초 로그인 시 AccessToken을 발급 받으면서 오류가 발생하는듯 합니다😢 

```
private GitHubTokenDto parseGithubTokenDto(String result) {
        try {
            JsonNode jsonNode = objectMapper.readTree(result);
            String accessToken = jsonNode.get("access_token").asText();
            String refreshToken = jsonNode.get("refresh_token").asText();
            return new GitHubTokenDto(accessToken, refreshToken);
        } catch (JsonProcessingException e) {
            throw new RuntimeException("Error parsing GitHub token response", e);
        }
    }
```

이 부분에서 `refreshToken`에 대한 정보를 받아오지 못하여 npe가 발생하는것 같습니다.
로그를 찍어보니 
``` 
{"access_token":"gho_m8acXVz~~~  ","token_type":"bearer","scope":""}
```
이러한 형식으로 refreshToken에 대한 필드는 존재하지 않는것 같습니다.
하단에 보다 정확한 에러 내용 첨부하겠습니다.
확인 부탁드립니다~

```
java.lang.NullPointerException: Cannot invoke "com.fasterxml.jackson.databind.JsonNode.asText()" because the return value of "com.fasterxml.jackson.databind.JsonNode.get(String)" is null
	at com.twoclock.gitconnect.openapi.github.service.GithubAPIService.parseGithubTokenDto(GithubAPIService.java:129) ~[main/:na]
	at com.twoclock.gitconnect.openapi.github.service.GithubAPIService.getMemberGitHubToken(GithubAPIService.java:47) ~[main/:na]
	at com.twoclock.gitconnect.domain.member.service.MemberAuthService.githubLogin(MemberAuthService.java:40) ~[main/:na]
	at com.twoclock.gitconnect.domain.member.web.MemberAuthController.githubLogin(MemberAuthController.java:20) ~[main/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:569) ~[na:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:255) ~[spring-web-6.1.11.jar:6.1.11]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:188) ~[spring-web-6.1.11.jar:6.1.11]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118) ~[spring-webmvc-6.1.11.jar:6.1.11]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:926) ~[spring-webmvc-6.1.11.jar:6.1.11]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:831) ~[spring-webmvc-6.1.11.jar:6.1.11]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-6.1.11.jar:6.1.11]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089) ~[spring-webmvc-6.1.11.jar:6.1.11]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979) ~[spring-webmvc-6.1.11.jar:6.1.11]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014) ~[spring-webmvc-6.1.11.jar:6.1.11]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903) ~[spring-webmvc-6.1.11.jar:6.1.11]
```

**Comment by openmpy** [comment]
@jjangsky 님~ 그게 버그가 아니라 GitHub Apps 에서 사진처럼 설정을 해주셔야 합니다.
<img width="1011" alt="스크린샷 2024-08-19 오전 12 45 30" src="https://github.com/user-attachments/assets/63127a32-3756-4723-8a80-deb2219cb776">

**Comment by jjangsky** [comment]
@openmpy  감사합니다~ 
바로 설정하겠습니다 !
